services:
  weaviate:
    container_name: weaviate-db
    command:
    - --host
    - 0.0.0.0
    - --port
    - '9035'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.0
    ports:
    - 9035:9035
    - 50051:50051
    restart: on-failure:0
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true' 
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'

  rag-server:
    container_name: rag-server
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - weaviate
    ports:
      - 8080:8080
    env_file:
      - ./.env

  frontend:
    container_name: rag-frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rag-server

volumes:
  weaviate_data: